<<<<<<< HEAD
baseURL = 'https://elita6.github.io/portfolio-site/'

=======
baseURL = 'https://elita6.github.io/portfolio-site/'  # 部署到 GitHub Pages 时改成你的实际网址
>>>>>>> 911f131 (Trigger first deploy)
languageCode = 'en-us'
title = 'Elita Portfolio'
theme = 'PaperMod'

# 站点参数
[params]
  defaultTheme = "auto" # auto, dark, light
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  ShowToc = true

# 菜单栏
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

