
baseURL = 'https://elita6.github.io/portfolio-site/'

languageCode = 'en-us'
title = 'Elita Portfolio'
theme = 'PaperMod'

# 
[params]
  defaultTheme = "auto" # auto, dark, light
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  ShowToc = true

# 
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
	[outputs]
  home = ["HTML", "RSS"]


