name: Deploy Hugo site to Pages + gh-pages branch

on:
  push:
    branches: ["main"]   # 你的源码分支
  workflow_dispatch:

permissions:
  contents: write        # 推送到 gh-pages 需要写权限
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout 代码（包含子模块）
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # 2. 安装 Hugo（Extended 版本）
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.149.1'   # 根据需要调整
          extended: true

      # 3. 构建站点
      - name: Build
        run: hugo --minify

      # 4. 上传构建产物（官方 Pages 用）
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

      # 5. 额外推送到 gh-pages 分支
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # 6. 官方 Pages 部署
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
